reviewApp/config/routes.rb
Rails.application.routes.draw do

  get 'sessions/index'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'static_pages/home'
  root 'static_pages#home'
  get 'static_pages/about'
    root 'static_pages#about'
  get 'static_pages/contact'
    root 'static_pages#contact'
  get 'static_pages/contact'
  resources :products, :shallow => true do
      resources :reviews
      
      collection do
  	   get :search
    end
    end
  resources :profiles
  resources :users, only: [:new, :create, :edit, :update]
  resources :sessions
  resources :password_resets
  resources :contacts


end

reviewApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

reviewApp/app/models/contact.rb
class Contact < ApplicationRecord
end

reviewApp/app/models/product.rb
class Product < ApplicationRecord
	has_many :reviews

	has_attached_file :image
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

reviewApp/app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user
	has_many :reviews

	has_attached_file :image
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

reviewApp/app/models/review.rb
class Review < ApplicationRecord
	belongs_to :user
	belongs_to :product
end

reviewApp/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates_uniqueness_of :email
  has_one :profile, dependent: :destroy
  has_many :reviews, dependent: :destroy




  def send_password_reset
    
    self.reset_digest = generate_token(:reset_digest)
    self.reset_sent_at = Time.zone.now
    save!
  	UserMailer.send_password_reset(self).deliver_later(wait: 1.second)
  	sleep 1
  end


##
def generate_token(column)
	begin
		self[column] = SecureRandom.urlsafe_base64
	end while  User.exists?(column => self[column])
end

def password_reset_expired?
  reset_sent_at < 2.hours.ago
end
##
end

reviewApp/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	def new
		@contact = Contact.new
	end

	def create
			
			@contact = Contact.last
			cname = params[:Cname]
			email = params[:email]
			subject = params[:subject]
			message = params[:message]
			ContactsMailer.general_message(cname, email, subject, message).deliver_now

	redirect_to root_path, notice: "Your enquiry has been sent successfully. We will reply as soon as possible."
	end

end

private def contact_params
params.require(:contact).permit(:cname, :email, :subject, :message)
	
end

reviewApp/app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def new
		@product = Product.new
	end

	def show
		@product = Product.find(params[:id])
		@reviews = Review.where(product_id: @product.id).order("Created_at DESC")
		@avg_review = @reviews.average(:rating)
		
	end

	def index
		@products = Product.all
	end

	def create
		@product = Product.new(product_params)
		if @product.save
			redirect_to @product
		else
			render 'new'
		end
	end

	def update

	end

	def edit
	end

	def destroy
	end

	def search
	@products = if params[:term]
		Product.where('pName LIKE ?', "%#{params[:term]}%")
	else
		Product.all
		end
		end


	private 
	def product_params 
		params.require(:product).permit(:pName, :brand, :averageCost, :category, :releaseDate, :description, :image)
	end
end

reviewApp/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
before_action :login_required

	def new
		@profile = current_user.build_profile
	end

	def show
		@profile = Profile.where(:user_id => params[:id]).first
	end

	def create
		@profile = current_user.build_profile(profile_params)
		if @profile.save
			redirect_to root_path
			UserMailer.welcome_email(current_user).deliver_now
		else
			render 'new'
		end
	end

	def update
		@profile = Profile.where(:user_id => params[:id]).first
		if @profile.update(profile_params)
			redirect_to root_path
		else
			render 'edit'
		end
	end

	def edit
		@profile = Profile.where(:user_id => params[:id]).first
	end

	def destroy
	end

	private 
	def profile_params 
		params.require(:profile).permit(:fullName, :dateOfBirth, :address, :cityORtown, :postcode, :country, :user_id, :image)
	end
end

reviewApp/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :login_required, only: [:create, :edit, :destroy]
  before_action :set_product, only: [:index, :create]
  before_action :set_profile, except: [:index]




  def index
    @reviews = Review.where(:product_id => @product).paginate(:page => params[:page], :per_page => 4)
  end

  def show
        @review = Review.find(params[:id])

  end

  def new
    @review = Review.new
  end

  def edit
    @review = Review.find(params[:id])
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.product_id = @product.id
    @review.author = @profile.fullName
    @review.image_file_name = @profile.image
      if @review.save
        redirect_to @product
      else
        render 'new'
      end
    end
  

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to @review
    else
      render 'edit'
    end
    end
  
def set_product
  @product = Product.find(params[:product_id])
end

def set_profile
            if current_user.present? 
@profile = Profile.where(:user_id => current_user.id).first
end end
 
  def destroy
          @review = Review.find(params[:id])
          @review.destroy
          redirect_back(fallback_location: root_path)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:author, :rating, :reviewText, :reviewDate, :user_id, :image_file_name)
    end
end

reviewApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new 
		@user = User.new
	end

	def create
		@user=User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to new_profile_path, notice: 
			"Welcome #{@user.userid}! to Congo. Please set up your profile."
		else
			render 'new'
		end
	end

	private def user_params
		params.require(:user).permit(:userid, :email, :password, :password_confirmation)
	end

end

reviewApp/app/helpers/application_helper.rb
module ApplicationHelper
end

reviewApp/app/helpers/contacts_helper.rb
module ContactsHelper
end

reviewApp/app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

reviewApp/app/helpers/products_helper.rb
module ProductsHelper
end

reviewApp/app/helpers/profiles_helper.rb
module ProfilesHelper
end

reviewApp/app/helpers/reviews_helper.rb
module ReviewsHelper
end

reviewApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

reviewApp/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

reviewApp/app/helpers/users_helper.rb
module UsersHelper
end

reviewApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Congo Reviews</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
   <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-normal"> Congo Reviews</h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark" href="#"> <%= link_to "Home", root_path %> </a>
        <a class="p-2 text-dark" href="#"> <%= link_to "About Us", static_pages_about_path %> </a>
        <a class="p-2 text-dark" href="#"> <%= link_to "Contact Form", new_contact_path %> </a>   
        <a class="p-2 text-dark" href="#"> <%= link_to 'Products', products_path %> </a>   
        <% if current_user %> 
                              <a class="p-2 text-dark dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= current_user.userid %></a>
                              <div class="dropdown-menu">
                               <a class="dropdown-item" href="#"> <%= link_to 'My Profile', profile_path(current_user.id) %></a>
                               <a class="dropdown-item" href="#"> <%= link_to 'Edit Profile', edit_profile_path(current_user.id) %></a>
                               <a class="dropdown-item" href="#"> <%= link_to 'Change Password', edit_user_path(current_user.id) %></a>
                             <a class="dropdown-item" href="#"><%=link_to 'Log-out', session_path('active'), method: :delete%></a>
                             </div>
                                
        <% else%>             <a class="p-2 text-dark" href="#"><%= link_to 'Log-In', new_session_path, class: "active_nav_link" %></a>
                <a class="p-2 text-dark" href="#"> <%= link_to 'Create Account', new_user_path %> </a>   

        <% end %>

      </nav>
    </div>
</div>
<div class ="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %>

    <%= yield %>
  </div>
  </body>
</html>