reviewApp/config/routes.rb
Rails.application.routes.draw do

  get 'sessions/index'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'static_pages/home'
  root 'static_pages#home'
  get 'static_pages/about'
    root 'static_pages#about'
  get 'static_pages/contact'
    root 'static_pages#contact'
  get 'static_pages/contact'
  resources :products, :shallow => true do
      resources :reviews
      
      collection do
  	   get :search
    end
    end
  resources :profiles
  resources :users, only: [:new, :create, :edit, :update]
  resources :sessions
  resources :password_resets
  resources :contacts


end

reviewApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

reviewApp/app/models/contact.rb
class Contact < ApplicationRecord
end

reviewApp/app/models/product.rb
class Product < ApplicationRecord
	has_many :reviews

	has_attached_file :image
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

reviewApp/app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user
	has_many :reviews

	has_attached_file :image
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

reviewApp/app/models/review.rb
class Review < ApplicationRecord
	belongs_to :user
	belongs_to :product
end

reviewApp/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates_uniqueness_of :email
  has_one :profile, dependent: :destroy
  has_many :reviews, dependent: :destroy




  def send_password_reset
    
    self.reset_digest = generate_token(:reset_digest)
    self.reset_sent_at = Time.zone.now
    save!
  	UserMailer.send_password_reset(self).deliver_later(wait: 1.second)
  	sleep 1
  end


##
def generate_token(column)
	begin
		self[column] = SecureRandom.urlsafe_base64
	end while  User.exists?(column => self[column])
end

def password_reset_expired?
  reset_sent_at < 2.hours.ago
end
##
end

reviewApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	def login_required
		redirect_to root_path, alert: "You must be logged in to access this page." if current_user.blank?

	end




	private
	def current_user
		@current_user ||=User.find(session[:user_id]) if session[:user_id]
	end
	helper_method :current_user
end

reviewApp/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	def new
		@contact = Contact.new
	end

	def create
			
			@contact = Contact.last
			cname = params[:Cname]
			email = params[:email]
			subject = params[:subject]
			message = params[:message]
			ContactsMailer.general_message(cname, email, subject, message).deliver_now

	redirect_to root_path, notice: "Your enquiry has been sent successfully. We will reply as soon as possible."
	end

end

private def contact_params
params.require(:contact).permit(:cname, :email, :subject, :message)
	
end

reviewApp/app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def new
		@product = Product.new
	end

	def show
		@product = Product.find(params[:id])
		@reviews = Review.where(product_id: @product.id).order("Created_at DESC")
		@avg_review = @reviews.average(:rating)
		
	end

	def index
		@products = Product.all
	end

	def create
		@product = Product.new(product_params)
		if @product.save
			redirect_to @product
		else
			render 'new'
		end
	end

	def update

	end

	def edit
	end

	def destroy
	end

	def search
	@products = if params[:term]
		Product.where('pName LIKE ?', "%#{params[:term]}%")
	else
		Product.all
		end
		end


	private 
	def product_params 
		params.require(:product).permit(:pName, :brand, :averageCost, :category, :releaseDate, :description, :image)
	end
end

reviewApp/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
before_action :login_required

	def new
		@profile = current_user.build_profile
	end

	def show
		@profile = Profile.where(:user_id => params[:id]).first
	end

	def create
		@profile = current_user.build_profile(profile_params)
		if @profile.save
			redirect_to root_path
			UserMailer.welcome_email(current_user).deliver_now
		else
			render 'new'
		end
	end

	def update
		@profile = Profile.where(:user_id => params[:id]).first
		if @profile.update(profile_params)
			redirect_to root_path
		else
			render 'edit'
		end
	end

	def edit
		@profile = Profile.where(:user_id => params[:id]).first
	end

	def destroy
	end

	private 
	def profile_params 
		params.require(:profile).permit(:fullName, :dateOfBirth, :address, :cityORtown, :postcode, :country, :user_id, :image)
	end
end

reviewApp/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :login_required, only: [:create, :edit, :destroy]
  before_action :set_product, only: [:index, :create]
  before_action :set_profile, except: [:index]




  def index
    @reviews = Review.where(:product_id => @product).paginate(:page => params[:page], :per_page => 4)
  end

  def show
        @review = Review.find(params[:id])

  end

  def new
    @review = Review.new
  end

  def edit
    @review = Review.find(params[:id])
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.product_id = @product.id
    @review.author = @profile.fullName
    @review.image_file_name = @profile.image
      if @review.save
        redirect_to @product
      else
        render 'new'
      end
    end
  

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to @review
    else
      render 'edit'
    end
    end
  
def set_product
  @product = Product.find(params[:product_id])
end

def set_profile
            if current_user.present? 
@profile = Profile.where(:user_id => current_user.id).first
end end
 
  def destroy
          @review = Review.find(params[:id])
          @review.destroy
          redirect_back(fallback_location: root_path)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:author, :rating, :reviewText, :reviewDate, :user_id, :image_file_name)
    end
end

reviewApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
  	redirect_to static_pages_home_path
  end

  def new
  end

  def create
  	#retrieves the registered user with given username
  	user=User.find_by_email(params[:email])
  	#authenticates using password of user and creates a session
  	if user && user.authenticate(params[:password])
  		session[:user_id]=user.id
  		redirect_to root_path, notice: "Welcome #{user.userid}, you are now logged in."

  		#If no matching username and password, redirect to login page and display error message
  	else
  		render 'new', notice: "Invalid Username and/or password"

  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_path, notice:"You have successfully logged out!"
  end
end

reviewApp/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

reviewApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new 
		@user = User.new
	end

	def create
		@user=User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to new_profile_path, notice: 
			"Welcome #{@user.userid}! to Congo. Please set up your profile."
		else
			render 'new'
		end
	end

	private def user_params
		params.require(:user).permit(:userid, :email, :password, :password_confirmation)
	end

end

reviewApp/app/helpers/application_helper.rb
module ApplicationHelper
end

reviewApp/app/helpers/contacts_helper.rb
module ContactsHelper
end

reviewApp/app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

reviewApp/app/helpers/products_helper.rb
module ProductsHelper
end

reviewApp/app/helpers/profiles_helper.rb
module ProfilesHelper
end

reviewApp/app/helpers/reviews_helper.rb
module ReviewsHelper
end

reviewApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

reviewApp/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

reviewApp/app/helpers/users_helper.rb
module UsersHelper
end

reviewApp/app/views/contacts/create.html.erb
<h1>Contacts#create</h1>
<p>Find me in app/views/contacts/create.html.erb</p>

reviewApp/app/views/contacts/new.html.erb
<div class="container">
	<h2>Contact Congo Reviews</h2>
	<%= form_for @contact do |f| %>
	<div class="field" style="100%">
		<% if @contact.errors.any? %>
		<div id="error_axplanation">
			<h2>
				<% pluralize(@contact.errors.count, "error") %>
			prohibited this from being saved. </h2>
			<p>
				<ul>
					<% @contact.errors.full_messages.each do |msg| %>
					<li>
						<%= msg %>
					</li>
				</ul>
				<% end %>
			</p>

			<% if alert %>
			<%= alert %>
			<% end %>
			</div> 
			<% end %>

			<%= text_field_tag :cname, nil, placeholder: 'Enter your name', class: 'form-control' %>
			<%= email_field_tag :email, nil, placeholder: 'Enter your Email', class: 'form-control' %>
			<%= text_field_tag :subject, nil, placeholder: 'Enter the subject of your enquiry', class: 'form-control' %>
			<%= text_area_tag :message, nil, placeholder: 'Enter the message of your enquiry', class: 'form-control' %>

			<%= f.submit 'Submit Enquiry' %>
			<% end %>
		</div>
	</div>

reviewApp/app/views/products/edit.html.erb
<div class="container">
	<h1>Edit Product</h1>
		<%= form_for @product, html: {multipart: true}, url: product_path do |f| %>
		<div class="form-group">
			<%= f.label :pName %>
			<%= f.text_field :pName, class:'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label :brand %>
			<%= f.text_field :brand, class:'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label :averageCost %>
			<%= f.number_field :averageCost, class:'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label :category %>
			<%= f.text_field :category, class:'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label :releaseDate %>
			<%= f.date_field :releaseDate, class:'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label :description %>
			<%= f.text_field :description, class:'form-control' %>
		</div>

		<div class="form-group">
			<%= f.label :image %>
			<%= f.file_field :image %>
		</div>


		<div class="form-group">
			<%= f.submit "Submit", class: 'btn btn-primary' %>
		</div>

		<div class="form-group">
			<%= link_to "Cancel", profiles_path%>
		</div>

		<% end %>
	</div>

reviewApp/app/views/products/index.html.erb
<% if !current_user %>
	<div class="jumbotron">
		<h1>Coconut Online Stores</h1>
		<p>You must be signed in to write a review of a product on our site.</p>
		<p><%= link_to "Sign-in", new_session_path, class: "btn btn-primary btn-lg" %></p>
	</div>
	<% end %>
	
<div class="container">
	<div class="<div class="form-control-flush"><%= form_tag search_products_path, method: :get do %>
	<tr><%= text_field_tag :term, nil, placeholder: 'Search', width: '80%' %>
	<%= submit_tag "Search", class:'btn btn-primary' %></tr>
</tr>
<% end %>
</div>
</br>

<div class="row" >

	<% @products.each do |product| %>

		<div class="col-sm-8 col-md-4 mmt-2"style="margin-bottom:5px"</div>
			<div class="card card-default" >	
				<div class="table-reviews">
					<ul class ="list-group list-group-flush">
						
						<li class="list-group-item">
							<div class="thumbnail">
								<%= link_to (image_tag product.image.url, size: "240x180", class: 'image'), product %>
							</div>
						</li>
						<li class="list-group-item" style="height: 80px"><strong>Product Name:</strong><br/>
				<%= product.pName %></li>
						<li class="list-group-item"><strong>Brand:</strong><br/>
				<%= product.brand %></li>
						<li class="list-group-item"><strong>Average Cost:</strong><br/>
				<%= product.averageCost %></li>
						<li class="list-group-item"><strong>Category:</strong><br/>
				<%= product.category %></li>
						<li class="list-group-item"><strong>Release Date:</strong><br/>
				<%= product.releaseDate %></li>
											<% if current_user.present? %>
<li class="list-group-item"style="height: 40px"><%= link_to 'Add Review', new_product_review_path(product) %><% end %>

						</li>
					</ul>
				</div>
			</div>
		</div>

	<% end %>
</div>


</div>

reviewApp/app/views/products/search.html.erb
<% if !current_user %>
	<div class="jumbotron">
		<h1>Coconut Online Stores</h1>
		<p>You must be signed in to write a review of a product on our site.</p>
		<p><%= link_to "Sign-in", new_session_path, class: "btn btn-primary btn-lg" %></p>
	</div>
	<% end %>
	
<div class="container">
	<div class="<div class="form-control-flush"><%= form_tag search_products_path, method: :get do %>
	<tr><%= text_field_tag :term, nil, placeholder: 'Search', width: '80%' %>
	<%= submit_tag "Search", class:'btn btn-primary' %><%= link_to "Clear Search", products_path, class:'btn btn-default' %></tr>
</tr>
<% end %>
</div>
</br>

<div class="row" >

	<% @products.each do |product| %>

		<div class="col-sm-8 col-md-4 mmt-2"style="margin-bottom:5px"</div>
			<div class="card card-default" >	
				<div class="table-reviews">
					<ul class ="list-group list-group-flush">
						
						<li class="list-group-item">
							<div class="thumbnail">
								<%= link_to (image_tag product.image.url, size: "240x180", class: 'image'), product %>
							</div>
						</li>
						<li class="list-group-item" style="height: 80px"><strong>Product Name:</strong><br/>
				<%= product.pName %></li>
						<li class="list-group-item"><strong>Brand:</strong><br/>
				<%= product.brand %></li>
						<li class="list-group-item"><strong>Average Cost:</strong><br/>
				<%= product.averageCost %></li>
						<li class="list-group-item"><strong>Category:</strong><br/>
				<%= product.category %></li>
						<li class="list-group-item"><strong>Release Date:</strong><br/>
				<%= product.releaseDate %></li>
											<% if current_user.present? %>
<li class="list-group-item"style="height: 40px"><%= link_to 'Add Review', new_product_review_path(product) %><% end %>

						</li>
					</ul>
				</div>
			</div>
		</div>

	<% end %>
</div>


</div>

reviewApp/app/views/products/show.html.erb
<div class="card card-default">
	<div class="card-body">
		<% if current_user.present? %><%= link_to "Add a review", new_product_review_path(@product) %><% end %>

		<div class="row">
			<div class="col-md-4 col-md-offset-2 mt-5">
					<%= image_tag @product.image.url,  size:'360x240' %>
										<!--Shows the average review score for the product -->
					<div class="star-rating" data-score= <%= @avg_review %> ></div>
					<em><%= "#{@reviews.length} reviews" %></em>
					<div class="table-responsive">
						<table class="table">
							<tbody>
								</br><tr>
									<td><strong>Product Name:</strong></td>
									<td><%= @product.pName %></td>
								</tr>
								<tr>
									<td><strong>Brand:</strong></td>
									<td><%= @product.brand %></td>
								</tr>
								<tr>
									<td><strong>Average Cost:</strong></td>
									<td><%= @product.averageCost %></td>
								</tr>
								<tr>
									<td><strong>Category:</strong></td>
									<td><%= @product.category %></td>
								</tr>
								<tr>
									<td><strong>Release Date:</strong></td>
									<td><%= @product.releaseDate %></td>
								</tr>
								<tr>
									<td><strong>Description:</strong></td>
									<td><%= @product.description %></td>
								</tr>

							</tbody>

						</table>
					</div>
			</div>

				<div class="col-md-6 offset-md-1 mt-5" align="center" >
					<h1 class="review_title"><%= @product.pName %> Reviews</h1>

					

					<% if @reviews.blank? %>
					                    <% if current_user.present? %>

					<h3>No Reviews addded yet, would you like to add the first?</h3>
					<%= link_to "Add First Review", new_product_review_path(@product), class:"btn btn-primary btn-lg" %> <% else %> <%= link_to "Log In To Leave A Review", new_session_path, class:"btn btn-primary btn-lg" %> <% end %>
					<% else %>
<%= link_to "View All #{@reviews.length} Reviews", product_reviews_path(@product) %>

					<% @reviews[0,3].each do |review| %>
					
					<div class="reviews">
						<div class="star-rating" data-score= <%= review.rating %> > <%= review.author %> | </div> <!--From Raty, uses stars with the data attached to the review.rating-->
						<div class="row"><div class="card-flush" align="center"><p><%= image_tag review.image_file_name,  size:'120x80', style: "border-radius: 100%" %></p></div>
						<div class="card-body offset-md-1" style="width: 50%; font-size: 80%;" ><p><%= review.reviewText %></p></div>

						 <% if current_user.present? %>
						
						<% if review.user_id == current_user.id %>

						<%= link_to 'Edit', edit_review_path(review.id) %>				
								| <%= link_to 'Delete', review_path(review.id), method: :Delete, data: {confirm: "Are you sure you want to delete your review?"} %>	<% end %><% end %><% end %>
							</div>	
					</div>
					
					<% end %>
			</div>
		</div>
	</div>
</div>
<!--script from raty-->
<script>
	$('.star-rating').raty({
		path: '/assets/',
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		}
	});
</script>

reviewApp/app/views/profiles/edit.html.erb
<div class="container">
	<h1>Edit Profile</h1>
		<%= form_for @profile, html: {multipart: true}, url: profile_path do |f| %>
					<div class="form-group">
			<%= f.label "Full Name:" %>
			<%= f.text_field :fullName, class:'form-control' %>
		</div>
		<div class="form-group">
			<%= f.hidden_field :user_id, :value => current_user.id  %>
		</div>
		<div class="form-group">
			<%= f.label "Date of Birth:" %>
			<%= f.date_field :dateOfBirth, class:'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label "Address:" %>
			<%= f.text_field :address, class:'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label "City/Town:" %>
			<%= f.text_field :cityORtown, class:'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label "Postcode:" %>
			<%= f.text_field :postcode, class:'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label "Country:" %>
			<%= f.text_field :country, class:'form-control' %>
		</div>
	
		<div class="form-group">
			<%= f.label "Profile Image" %>
			<%= f.file_field :image %>
		</div>

		<div class="form-group">
			<%= f.submit "Submit", class: 'btn btn-primary' %>
		</div>

		<div class="form-group">
			<%= link_to "Cancel", profiles_path%>
		</div>

		<% end %>
	</div>

reviewApp/app/views/profiles/new.html.erb
<div class="container">
	<h1>Create Profile</h1>
		<%= form_for :profile, html: { multipart: true}, url: profiles_path do |f| %>
				<div class="form-group">
			<%= f.hidden_field :user_id, :value => current_user.id  %>
		</div>
		<div class="form-group">
			<%= f.label "Date of Birth:" %>
			<%= f.date_field :dateOfBirth, class:'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label "Address:" %>
			<%= f.text_field :address, class:'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label "City/Town:" %>
			<%= f.text_field :cityORtown, class:'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label "Postcode:" %>
			<%= f.text_field :postcode, class:'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label "Country:" %>
			<%= f.text_field :country, class:'form-control' %>
		</div>
	
		<div class="form-group">
			<%= f.label "Profile Image" %>
			<%= f.file_field :image %>
		</div>


		<div class="form-group">
			<%= f.submit "Submit", class: 'btn btn-primary' %>
		</div>

		<div class="form-group">
			<%= link_to "Cancel", profiles_path%>
		</div>

		<% end %>
	</div>

reviewApp/app/views/profiles/show.html.erb
<div class="container">
			<div class="row">
<div class="card col-md-12" style="align: center">
					<div class="col-md-12 col-md-offset-6 mt-2">
<h3><strong><%= @profile.fullName %>'s Profile</strong></h3>
	<p><%= image_tag @profile.image.url,  size:'200x150' %></p>	
	<p><strong>Full Name: </strong>					<br/><%= @profile.fullName %></p>
	<p><strong>Date of Birth: </strong>	<br/>		<%= @profile.dateOfBirth %></p>
	<p><strong>Address:</strong> 		<br/>	<%= @profile.address %></p>
	<p><strong>City/Town: </strong><br/>	<%= @profile.cityORtown %></p>
	<p><strong>Postcode:</strong> <br/>	<%= @profile.postcode %></p>
	<p><strong>Country: </strong>	<br/><%= @profile.country %></p>
	<p><%= link_to 'Edit Profile', edit_profile_path(current_user.id) %></p>
	<p><%= link_to 'Back', :back %></p>
</div>
</div></div>

reviewApp/app/views/users/new.html.erb
<div class="container">
	<h2>Create User Account</h2>
	<%= form_for @user do |f| %>
	<div class="field" style="100%">
		<% if @user.errors.any? %>
		<div id="error_axplanation">
			<h2>
				<% pluralize(@user.errors.count, "error") %>
			prohibited this from being saved. </h2>
			<p>
				<ul>
					<% @user.errors.full_messages.each do |msg| %>
					<li>
						<%= msg %>
					</li>
				</ul>
				<% end %>
			</p>

			<% if alert %>
			<%= alert %>
			<% end %>
			</div> 
			<% end %>

			<%= f.text_field :userid, placeholder: 'Enter a username', class: 'form-control' %>
			<%= f.email_field :email, placeholder: 'Enter your Email', class: 'form-control' %>
			<%= f.password_field :password, placeholder: 'Create a Password', class: 'form-control' %>
			<%= f.password_field :password_confirmation, placeholder: 'Confirm password', class: 'form-control' %>

			<%= f.submit 'Create Account' %>
			<% end %>
		</div>
	</div>